name: Deploy Next.js App

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Executar Script de Deploy
        run: |
          chmod +x deploy.sh
          ./deploy.sh v1.0.0
